### ISSUE TITLE
Construct `rse_tx` for rat

### ISSUE THREAD

**Issue by Nick-Eagles** [LieberInstitute/SPEAQeasy#94]
While we actually perform transcript quantification (via Kallisto/Salmon) for rat, we never construct the final `SummarizedExperiment` object `rse_tx`. A couple pieces are missing: a `feature_to_Tx*.rda` object must be built (see [annotation objects script](https://github.com/LieberInstitute/SPEAQeasy/blob/712ad37656dfefc16c9285827e044caed1066a33/scripts/build_annotation_objects.R#L114)), Kallisto/Salmon outputs should be read in (see [here](https://github.com/LieberInstitute/SPEAQeasy/blob/712ad37656dfefc16c9285827e044caed1066a33/scripts/create_count_objects.R#L290)), [transcript maps must be added](https://github.com/LieberInstitute/SPEAQeasy/blob/712ad37656dfefc16c9285827e044caed1066a33/scripts/create_count_objects.R#L758), and the [final `rse_tx` must be constructed](https://github.com/LieberInstitute/SPEAQeasy/blob/712ad37656dfefc16c9285827e044caed1066a33/scripts/create_count_objects.R#L1049).

**Comment by gpertea** [comment]
If it helps: I already tackled most of this issue in the `gjhpce_run` branch  for the custom reference/annotation case that I had to deal with -- and in my approach, anything that wasn't Gencode was considered "custom", essentially. 

Parsing the salmon/kallisto transcript output (in order to build the transcript map) depends on how the transcriptome file was built -- e.g. I did it with gffread which only puts the transcript_id in the tx FASTA file, so that's the only ID you get in the resulting salmon/kallisto quantification file, so you have to build that transcript map based on joining those with the annotation objects  e.g. https://github.com/LieberInstitute/SPEAQeasy/blob/gjhpce_run/scripts/create_count_objects.R#L382

**Comment by Nick-Eagles** [comment]
While this is mostly solved now, I'll leave the issue open due to [this problematic code](https://github.com/LieberInstitute/SPEAQeasy/blob/84d2661d5b2e304851080fdfeb145377a87b0d6f/scripts/create_count_objects.R#L359-L371) which should likely be changed. For default rat runs (which currently use rn6 with ensembl version 98), not all transcripts from the reference FASTA are in the GTF, and the names don't quite match. This should be further investigated

**Comment by gpertea** [comment]
How was the transcriptome FASTA file obtained? Using e.g. gffread to generate it from the GTF and the genome FASTA, there should be a 1-to-1 correspondence between the `transcript_id` attribute in the GTF and the sequence ID in the FASTA headers - and that transcript ID will be the one that salmon/kallisto writes in the output abundance file.

I recall that for the Gencode data, the transcriptome FASTA they provide for download has a bunch of attributes from the GTF (beginning with the `transcript_id`) concatenated using the '|' character.

**Comment by Nick-Eagles** [comment]
That's what I expected, but the Kallisto outputs have a `.1` or similar in the transcript name compared to the `transcript_id` attribute in the GTF. [This code] specifies where the GTF and FASTA come from, which I would think should be compatible. After removing the `.1` or similar suffix, almost all of the transcript IDs are present in the GTF

**Comment by Nick-Eagles** [comment]
Just discovered that the "main" transcripts FASTA actually contains non-chromosomal sequences (i.e. "primary" sequences), and there is a 1-to-1 correspondence after subsetting the FASTA to the chromosomal transcripts and removing the `.1` or similar suffix... so I'll fix the code to process the transcripts FASTA appropriately for "main" annotation
